spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          format_sql: true
      show-sql: true

  redis:
    port: ${REDIS_PORT}
    host: ${REDIS_HOST}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GOOGLE_USERNAME}
    password: ${GOOGLE_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            protocols: TLSv1.3
          starttls:
            enable: true
            required: true
        debug: true
    default-encoding: UTF-8

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8

  main:
    allow-bean-definition-overriding: true

  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      fail-on-empty-beans: false

jwt:
  secret_key: ${JWT_SECRET_KEY}
  access_exp: ${JWT_ACCESS_EXP}
  refresh_exp: ${JWT_REFRESH_EXP}
  header: ${JWT_HEADER}
  prefix: ${JWT_PREFIX}

cloud:
  aws:
    access_key: ${AWS_ACCESS_KEY}
    secret_key: ${AWS_SECRET_KEY}
    bucket: ${AWS_BUCKET}
    url: ${BASE_URL}
    region:
      static: ap-northeast-2
    stack:
      auto: false

app:
  profile: ${DEFAULT_PROFILE}
